// default package
// Generated 2017-6-27 10:42:03 by Hibernate Tools 3.6.0.Final

/**
 * Order generated by hbm2java
 */
public class Order implements java.io.Serializable {

	private int orderid;
	private int userid;
	private int username;

	private int 123;

    public Order() {
    }

	public Order(int orderid, int userid, int username, int 123) {
       this.orderid = orderid;
       this.userid = userid;
       this.username = username;
       this.123 = 123;
    }

	public int getOrderid() {
		return this.orderid;
	}

	public void setOrderid(int orderid) {
		this.orderid = orderid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public int getUsername() {
		return this.username;
	}

	public void setUsername(int username) {
		this.username = username;
	}

	public int get123() {
        return this.123;
    }

	public void set123(int 123) {
        this.123 = 123;
    }




}
