// default package
// Generated 2017-6-27 10:42:03 by Hibernate Tools 3.6.0.Final

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private int testid;

	private int 1231;

    public Test() {
    }

	public Test(int testid, int 1231) {
       this.testid = testid;
       this.1231 = 1231;
    }

	public int getTestid() {
		return this.testid;
	}

	public void setTestid(int testid) {
		this.testid = testid;
	}

	public int get1231() {
        return this.1231;
    }

	public void set1231(int 1231) {
        this.1231 = 1231;
    }




}
